// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShadEntityFrameworkApp.Models;

namespace ShadEntityFrameworkApp.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20201119132148_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ShadEntityFrameworkApp.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("EmpCode")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("EmpCode");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("FullName");

                    b.Property<string>("OfficeLocation")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("OfficeLocation");

                    b.Property<string>("Position")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Position");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
